### ISSUE TITLE
Chrome kills the extension because it's not from the Chrome Web Store

### ISSUE THREAD

**Issue by matt-chapman** [Chronophobe/uba-webext#1]
Chrome just threw a fit and disabled the extension, pointing me to this page:

https://support.google.com/chrome/answer/2811969?visit_id=1-636263762677629723-1012660916&p=ui_remove_non_cws_extensions&rd=1

I can't re-enable the extension even in Developer mode, and the enable box is greyed out with the message "Not from Chrome Web Store".

Could you upload it there? :)

**Comment by Chronophobe** [comment]
I encountered this issue too, but I couldn't really be bothered with uploading it at the time.
And apparently you need to pay $5,- to upload up to 20 extensions to the Web Store.

If you do prefer it over the bookmarklet, you can install it using the alternative guidelines from the readme (see below).
> In case Chrome blocks the extension since it's installed outside the Web Store, use the following steps:
> 
> 1.    Clone the source
> 2.    Go to More tools > Extensions
> 3.    Make sure the Developer mode checkbox is ticked.
> 4.    Select Load unpacked extension...
> 5.    Select the chrome directory from the cloned source.

I'd be happy to upload it for a beer or two. ;)

**Comment by matt-chapman** [comment]
Huh, I had no idea the web store charged! Also, I should have read the readme in it's entirety :)

Cheers!
